version: "3.8"

services:
  dionysus-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: dionysus-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - dionysus3-core_default
      # - dionysus_default
    restart: unless-stopped

networks:
  dionysus3-core_default:
    external: true
  # dionysus_default:
  #   external: true
